/* Allegro datafile object indexes, produced by grabber v3.0 */
/* Datafile: d:\c\kei\kc\sfchar.dat */
/* Date: Wed May  6 23:43:14 1998 */
/* Do not hand edit! */

#define GRN                              0        /* BMP  */
#define ORG                              1        /* BMP  */
#define PAL_GAME                         2        /* PAL  */
#define SELECT                           3        /* BMP  */

